### PR TITLE
save detectorMapQA pdfs in rerun using butler - PIPE2D-1370

### PR DESCRIPTION
**Pull request by wtgee**
* Adding output connections for PDF to butler.'

Depends on https://github.com/Subaru-PFS/obs_pfs/pull/155

### CODE REVIEW

**Comment by wtgee** [comment]
This code runs but I can't seem to access the PDF from the butler afterward, even using my local copy of `obs_pfs` with the policy mapper changes. I assume it would be with the same name, i.e. `butler.get('dmQaResidualImage`, **dataId)`.

@SogoMineo or @PaulPrice any suggestions?

edit: I might not have been passing it all the way up the call chain properly because the PlotResidualTask is within the DetectorMapQaTask.  I'll take another look and see if I can figure it out.

**Comment by wtgee** [comment]
@SogoMineo @PaulPrice @kiyoyabe 

I'm trying to understand how to set this up properly by following the extractionQA example, however there are some differences that are giving me problems.

The `DetectorMapQaTask` is a `CmdLineTask, PipelineTask` and so the `DetectorMapQaConfig` has a `pipelineConnections=DetectorMapQaConnections` that defines the mapping to save to butler. This is copied from how the extraction QA setup stuff is done.

The problem is that I don't output directly from the `DetectorMapQaTask` but the `PlotResidualTask`, which is not a `PipelineTask` and so has no `pipelineConnections`. I tried to just add this but no luck. 

How do I save to butler via a subtask?

**Comment by PaulPrice** [comment]
In the Gen3 middleware, the I/O and the computation get separated. Have the `PlotResidualTask` return the outputs to the `DetectorMapQaTask` for it to write.

**Comment by wtgee** [comment]
> In the Gen3 middleware, the I/O and the computation get separated. Have the `PlotResidualTask` return the outputs to the `DetectorMapQaTask` for it to write.

Thanks, I think I have it figured out. I was a bit confused because this also uses a separate runner and is grouping across detectors. I just talked with @kiyoyabe about it and what we want so I will get it cleaned up over the weekend and let you know if I have any more problems.

**Comment by SogoMineo** [comment]
> This code runs but I can't seem to access the PDF from the butler afterward, even using my local copy of `obs_pfs` with the policy mapper changes. I assume it would be with the same name, i.e. `butler.get('dmQaResidualImage`, **dataId)`.

You are right.
(gen2) https://github.com/lsst-dm/legacy-daf_persistence/blob/17e5ecfddbd1d20bef02015b6e9ac03c522e939e/python/lsst/daf/persistence/posixStorage.py#L831
(gen3) https://github.com/lsst/daf_butler/blob/6308b79845bd954eea6783906e5f0de9d69791be/python/lsst/daf/butler/formatters/matplotlib.py#L45

Matplotlib's Figure object cannot be reconstructed from PNG or PDF files.

**Comment by SogoMineo** [comment]
WIth gen2 butler, you can get the path to a PDF by `butler.get("dmQaResidualImage_filename", **dataId)` etc. See https://github.com/lsst/obs_base/blob/baa45dfa326e5557439893fd13d7a383ec0652f9/python/lsst/obs/base/cameraMapper.py#L463

**Comment by wtgee** [comment]
> WIth gen2 butler, you can get the path to a PDF by `butler.get("dmQaResidualImage_filename", **dataId)` etc. See https://github.com/lsst/obs_base/blob/baa45dfa326e5557439893fd13d7a383ec0652f9/python/lsst/obs/base/cameraMapper.py#L463

This doesn't work with a `ValueError: Empty module name`.  The PDFs are created and I can see them in the rerun directory.

**Comment by wtgee** [comment]
> > WIth gen2 butler, you can get the path to a PDF by `butler.get("dmQaResidualImage_filename", **dataId)` etc. See https://github.com/lsst/obs_base/blob/baa45dfa326e5557439893fd13d7a383ec0652f9/python/lsst/obs/base/cameraMapper.py#L463
> 
> This doesn't work with a `ValueError: Empty module name`. The PDFs are created and I can see them in the rerun directory.

I can solve this by changing the `python: object` mapping in `obs_pfs` `policy/PfsMapper.yaml` to a valid something. I did `matplotlib.figure.Figure` and it gives the filename properly even though that's not the python type. 🤷🏼

**Review by kiyoyabe — APPROVED** [review]
Thanks. I confirmed it worked as I expected.

**Pull request merged**
